import React from "react";
import { Heart, Github, Code2 } from "lucide-react";

export const Footer: React.FC = () => {
  return (
    <footer className="bg-[#2E1A47] text-white py-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          {/* Brand Section */}
          <div className="space-y-4">
            <div className="flex items-center">
              <Code2 className="w-8 h-8 text-[#FFC857] mr-3" />
              <h3 className="text-2xl font-bold">React PWA Template</h3>
            </div>
            <p className="text-white/70 leading-relaxed">
              A modern, comprehensive starter template for building Progressive
              Web Apps with React, TypeScript, and all the tools you need for
              production-ready applications.
            </p>
            <div className="flex items-center text-sm text-white/60">
              <span>Made with</span>
              <Heart className="w-4 h-4 text-red-400 mx-2 fill-current" />
              <span>for the developer community</span>
            </div>
          </div>

          {/* Quick Links */}
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-[#FFC857]">
              Quick Links
            </h4>
            <ul className="space-y-3">
              <li>
                <a
                  href="https://github.com/MikeKomari/ReactTSPWATemplate"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/70 hover:text-white transition-colors duration-200 flex items-center"
                >
                  <Github className="w-4 h-4 mr-2" />
                  GitHub Repository
                </a>
              </li>
              <li>
                <a
                  href="https://github.com/MikeKomari/ReactTSPWATemplate#readme"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/70 hover:text-white transition-colors duration-200"
                >
                  README Guide
                </a>
              </li>
              <li>
                <a
                  href="https://github.com/MikeKomari/ReactTSPWATemplate#-quick-start"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/70 hover:text-white transition-colors duration-200"
                >
                  Getting Started Guide
                </a>
              </li>
              <li>
                <a
                  href="https://github.com/MikeKomari/ReactTSPWATemplate/issues"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-white/70 hover:text-white transition-colors duration-200"
                >
                  Issues & Support
                </a>
              </li>
            </ul>
          </div>

          {/* Features */}
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-[#FFC857]">
              Key Features
            </h4>
            <ul className="space-y-3 text-white/70">
              <li>• React 19 + TypeScript</li>
              <li>• Progressive Web App Ready</li>
              <li>• Modern State Management</li>
              <li>• Testing Suite Included</li>
              <li>• Production Optimized</li>
              <li>• Developer Experience Focus</li>
            </ul>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-white/20 mt-12 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="text-white/60 text-sm mb-4 md:mb-0">
              © 2025 React PWA Template. This page is generated by Bolt AI.
            </div>
            <div className="text-white/60 text-sm">
              Created by{" "}
              <span className="text-[#FFC857] font-semibold">Mike</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};
